# House Price Prediction Using Linear Regression

## Objective

The objective of this project is to build a Linear Regression model that predicts the price of a house based on its features such as area, number of bedrooms, bathrooms, stories, parking spaces, and other amenities.

## Dataset

- Source: Kaggle
- Dataset: Housing Prices Dataset
- Target Variable: Price

## Workflow

1. Import Libraries
2. Load Dataset
3. Explore the Dataset
4. Clean the Data
5. Perform Exploratory Data Analysis (EDA)
6. Preprocess the Data
7. Split the Data into Training and Testing Sets
8. Train a Linear Regression Model
9. Evaluate the Model
10. Draw Conclusions

In [1]:
# Data Manipulation
import numpy as np
import pandas as pd

# Data Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

# Display plots inside notebook
%matplotlib inline

### Import Dataset

In [5]:
df = pd.read_csv("../data/housing-prices-dataset/Housing.csv")

### Data Explortion

In [ ]:
df.head()

      price  area  bedrooms  ...  parking  prefarea furnishingstatus
0  13300000  7420         4  ...        2       yes        furnished
1  12250000  8960         4  ...        3        no        furnished
2  12250000  9960         3  ...        2       yes   semi-furnished
3  12215000  7500         4  ...        3       yes        furnished
4  11410000  7420         4  ...        2        no        furnished

[5 rows x 13 columns]

In [ ]:
df.shape    # (rows, columns)

(545, 13)

In [ ]:
df.columns  # All columns in the dataset

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='str')

In [10]:
df.info()   # Data types of each column and non-null counts

<class 'pandas.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    str
 6   guestroom         545 non-null    str
 7   basement          545 non-null    str
 8   hotwaterheating   545 non-null    str
 9   airconditioning   545 non-null    str
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    str
 12  furnishingstatus  545 non-null    str
dtypes: int64(6), str(7)
memory usage: 55.5 KB

In [11]:
df.describe()  # Summary statistics of the numerical columns

              price          area  ...     stories     parking
count  5.450000e+02    545.000000  ...  545.000000  545.000000
mean   4.766729e+06   5150.541284  ...    1.805505    0.693578
std    1.870440e+06   2170.141023  ...    0.867492    0.861586
min    1.750000e+06   1650.000000  ...    1.000000    0.000000
25%    3.430000e+06   3600.000000  ...    1.000000    0.000000
50%    4.340000e+06   4600.000000  ...    2.000000    0.000000
75%    5.740000e+06   6360.000000  ...    2.000000    1.000000
max    1.330000e+07  16200.000000  ...    4.000000    3.000000

[8 rows x 6 columns]